// <auto-generated />
using System;
using Api.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Shared.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ParentCategoryID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B99971774");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Api.Shared.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21A96FAB7A431");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Api.Shared.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CountryId")
                        .HasName("PK__Countrie__10D160BFA6A10B3C");

                    b.HasIndex(new[] { "Name" }, "UQ__Countrie__737584F6038A11C2")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Api.Shared.Models.Directory", b =>
                {
                    b.Property<int>("DirectoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DirectoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("DirectoryId")
                        .HasName("PK__Director__3D93EF02310A129E");

                    b.HasIndex(new[] { "TenantId" }, "IX_Directories_TenantID");

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("Api.Shared.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatalogUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("ListingId")
                        .HasName("PK__Listings__BF3EBEF015E53387");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Listings_CategoryID");

                    b.HasIndex(new[] { "TenantId" }, "IX_Listings_TenantID");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingDirectory", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<int>("DirectoryId")
                        .HasColumnType("int")
                        .HasColumnName("DirectoryID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId", "DirectoryId")
                        .HasName("PK__ListingD__8CE7800067021207");

                    b.ToTable("ListingDirectories");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingHour", b =>
                {
                    b.Property<int>("ListingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListingHourID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingHourId"));

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("ListingHourId")
                        .HasName("PK__ListingH__592C613EFBDC1CE4");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingHours_ListingID");

                    b.ToTable("ListingHours");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingImage", b =>
                {
                    b.Property<int>("ListingImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListingImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingImageId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ListingImageId")
                        .HasName("PK__ListingI__C6DC7267363AC772");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingImages_ListingID");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingPaymentMethod", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethodID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId", "PaymentMethodId")
                        .HasName("PK__ListingP__92FDA2EF060DA934");

                    b.ToTable("ListingPaymentMethods");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingPhone", b =>
                {
                    b.Property<int>("ListingPhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListingPhoneID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingPhoneId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ListingPhoneId")
                        .HasName("PK__ListingP__173A7A4BF4234577");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingPhones_ListingID");

                    b.ToTable("ListingPhones");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingService", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId", "ServiceId")
                        .HasName("PK__ListingS__036F05FE36A3A0AF");

                    b.ToTable("ListingServices");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingSocialLink", b =>
                {
                    b.Property<int>("ListingSocialLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListingSocialLinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingSocialLinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ListingSocialLinkId")
                        .HasName("PK__ListingS__F35A644047C0C02F");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingSocialLinks_ListingID");

                    b.ToTable("ListingSocialLinks");
                });

            modelBuilder.Entity("Api.Shared.Models.ListingTag", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("ListingID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId", "TagId")
                        .HasName("PK__ListingT__69697154B3470137");

                    b.ToTable("ListingTags");
                });

            modelBuilder.Entity("Api.Shared.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1F3A5B8D7A3");

                    b.HasIndex(new[] { "TenantId" }, "IX_PaymentMethods_TenantID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Api.Shared.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ProvinceId")
                        .HasName("PK__Province__FD0A6FA393A5CE47");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Api.Shared.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A5E3654EA");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6B9F64D24")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Api.Shared.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB0EAA74C382E");

                    b.HasIndex(new[] { "TenantId" }, "IX_Services_TenantID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Api.Shared.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("TagId")
                        .HasName("PK__Tags__657CFA4C3DE630B2");

                    b.HasIndex(new[] { "TenantId" }, "IX_Tags_TenantID");

                    b.HasIndex(new[] { "Name" }, "UQ__Tags__737584F6F04CCD75")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Api.Shared.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenantId")
                        .HasName("PK__Tenants__2E9B47813336E98C");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Api.Shared.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImgProfile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC2B1B6163");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Users_TenantID")
                        .HasFilter("([TenantID] IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053443B3B561")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Shared.Models.Category", b =>
                {
                    b.HasOne("Api.Shared.Models.User", "CreatedByUser")
                        .WithMany("CategoryCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Categories_CreatedByUser");

                    b.HasOne("Api.Shared.Models.User", "ModifiedByUser")
                        .WithMany("CategoryModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("FK_Categories_ModifiedByUser");

                    b.HasOne("Api.Shared.Models.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_Categories_Self_Parent");

                    b.HasOne("Api.Shared.Models.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Categories_Tenants");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("ParentCategory");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Api.Shared.Models.City", b =>
                {
                    b.HasOne("Api.Shared.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK_Cities_Provinces");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Api.Shared.Models.Province", b =>
                {
                    b.HasOne("Api.Shared.Models.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_Provinces_Countries");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Api.Shared.Models.Tenant", b =>
                {
                    b.HasOne("Api.Shared.Models.City", "City")
                        .WithMany("Tenants")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Tenants_Cities");

                    b.HasOne("Api.Shared.Models.User", "CreatedByUser")
                        .WithMany("TenantCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Tenants_CreatedByUser");

                    b.HasOne("Api.Shared.Models.User", "ModifiedByUser")
                        .WithMany("TenantModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("FK_Tenants_ModifiedByUser");

                    b.Navigation("City");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("Api.Shared.Models.User", b =>
                {
                    b.HasOne("Api.Shared.Models.User", "CreatedByUser")
                        .WithMany("InverseCreatedByUser")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Users_CreatedByUser");

                    b.HasOne("Api.Shared.Models.User", "ModifiedByUser")
                        .WithMany("InverseModifiedByUser")
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("FK_Users_ModifiedByUser");

                    b.HasOne("Api.Shared.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.HasOne("Api.Shared.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Users_Tenants");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Api.Shared.Models.Category", b =>
                {
                    b.Navigation("InverseParentCategory");
                });

            modelBuilder.Entity("Api.Shared.Models.City", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Api.Shared.Models.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Api.Shared.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Api.Shared.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Api.Shared.Models.Tenant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Api.Shared.Models.User", b =>
                {
                    b.Navigation("CategoryCreatedByUsers");

                    b.Navigation("CategoryModifiedByUsers");

                    b.Navigation("InverseCreatedByUser");

                    b.Navigation("InverseModifiedByUser");

                    b.Navigation("TenantCreatedByUsers");

                    b.Navigation("TenantModifiedByUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
