<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<NoWarn>$(NoWarn);ASP0014</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="EPPlus" Version="7.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Api.Shared\Api.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\Services\" />
	</ItemGroup>

</Project>
